### ISSUE TITLE
관리자>전자공고 이미지 렌더링 사이즈 수정

### ISSUE THREAD

**Issue by KANG-MOON-SUN** [huyndaiAsan/AsanWeb#8]
아산 관리자 내 전자공고
사진 등록 시 이미지 렌더링 사이즈 수정

**Comment by KANG-MOON-SUN** [comment]
안녕하세요.
기획팀 강문선입니다:)

@MooGyo  차장님,

아산 관리자> 전자공고 내 사진 등록 시
![image](https://user-images.githubusercontent.com/102637517/161653880-dfe0fa10-ee48-4156-ac2d-7ebea34f3d4b.png)

현재 width=700으로 고정되는데 900으로 들어갈 수 있도록 수정 가능하다면 수정 부탁드리겠습니다.
![image](https://user-images.githubusercontent.com/102637517/161653955-03a6e0fb-3bc5-40d4-997a-d68f3637c148.png)

확인 부탁드립니다.
감사합니다.

**Comment by MooGyo** [comment]
@KANG-MOON-SUN
운영 반영 되는 것 확인 되면 해당 이슈 close 해주세요.
